#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;31mESPERE SENTADO 🐲🏴 \033[1;37m- \033[1;31m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;31m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;31mESPERE SENTADO 🐲🏴 \033[1;37m- \033[1;31m["
done
echo -e "\033[1;31m]\033[1;37m -\033[1;31m OK !\033[1;37m"
tput cnorm
}
clear
echo -e "\033[1;31m╔═══════════════════════════════════════╗\033[0m"
tput setaf 7 ; tput setab 1 ; tput bold ; printf '%40s%s%-12s\n' "NETXXUS SLOWDNS INSTALLER 🐲🏴" ; tput sgr0
echo -e "\033[1;31m╚═══════════════════════════════════════╝\033[0m"
echo -e ""
echo -e "    \033[1;37mInstalador en castellano AR\033[0m"
echo -e "    \033[1;37mSlowDNS conecion mode.\033[0m"
echo -e ""
echo -e "         \033[1;31mModded/Translated by t.me/NetxxusVPN 🐲🏴 \033[1;37m"
echo -e "\033[1;31m╠═══════════════════════════════════════╣\033[0m"
echo ""
echo -e "\033[1;37mDOWNLOADING DEPENDENCIES...\033[0m"
echo ""
fun_att () {
apt install ncurses-utils -y
mkdir /etc/slowdns
cd /etc/slowdns
wget https://github.com/khaledagn/DNS-AGN/raw/main/dns-server; chmod +x dns-server
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/remove-slow; chmod +x remove-slow
wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/refs/heads/main/Slowdns/slowdns-info; chmod +x slowdns-info
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/slowdns-drop; chmod +x slowdns-drop
wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/refs/heads/main/slowdns-ssh; chmod +x slowdns-ssh
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/slowdns-ssl; chmod +x slowdns-ssl
wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/refs/heads/main/Slowdns/slowdns-socks; chmod +x slowdns-socks
wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/refs/heads/main/Slowdns/slowdns; chmod +x slowdns; cp slowdns /bin/
wget https://raw.githubusercontent.com/vpsvip7/SSHPLUS/refs/heads/main/Slowdns/stopdns; chmod +x stopdns
}
fun_bar 'fun_att'
echo -e "\033[1;37mCONFIGURANDO FIREWALL...\033[0m"
echo ""
fun_ports () {
apt update
}
fun_bar 'fun_ports'
echo -e "\033[1;37mAjustes CLOUDFLARE DNS...\033[0m"
echo ""
fun_dnscf () {
apt update
sleep 2
}
fun_bar 'fun_dnscf'
clear
echo -e "\033[1;31m╔═══════════════════════════════════════╗\033[0m"
tput setaf 7 ; tput setab 1 ; tput bold ; printf '%40s%s%-12s\n' "NETXXUS SLOWDNS INSTALLER 🐲🏴" ; tput sgr0
echo -e "\033[1;31m╚═══════════════════════════════════════╝\033[0m"
echo ""
echo -e "          \033[1;31mINSTALLACION COMPLETADO! 🐲🏴\033[0m          "
echo ""
echo -e "\033[1;37mPara abrir el menu, use el comando: \033[1;31mslowdns\033[0m"
cd
rm -rf install2
