#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;31mESPERE SENTADO 🐲🏴 \033[1;37m- \033[1;31m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;31m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;31mESPERE SENTADO 🐲🏴 \033[1;37m- \033[1;31m["
done
echo -e "\033[1;31m]\033[1;37m -\033[1;31m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m╔══════════════════════════════════════════════════╗\033[0m"
tput setaf 7 ; tput setab 1 ; tput bold ; printf '%40s%s%-12s\n' "NETXXUS SLOW DNS SSH 🐲🏴" ; tput sgr0
echo -e "\033[1;31m╚══════════════════════════════════════════════════╝\033[0m"
echo -e ""
echo -e "      \033[1;37mThis script will install the\033[0m"
echo -e "     \033[1;37mslowdns for DNS tunneling with SSH.\033[0m"
echo -e ""
echo -e "         \033[1;31mInstaller made by @Laael and Modded/Translated by t.me/NetxxusVPN 🐲🏴 \033[1;37m"
echo -e ""
echo -e "\033[1;31m╠══════════════════════════════════════════════════╣\033[0m"
echo ""
echo -e "\033[1;37mUPDATING PACKAGE LIST...\033[0m"
fun_att () {
apt update 
}
fun_bar 'fun_att'
echo -e "\033[1;37mINSTALLING AND UPDATING NECESSARY PACKAGES...\033[0m"
install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "\033[1;37mCONFIGURING IPTABLES...\033[0m"
ipt_set () {
cd /etc
mv rc.local rc.local.bkp
wget https://github.com/khaledagn/SlowDNS/raw/main/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m ATENCION IN THIS STAGE! 🐲🏴 \033[1;33m"
echo ""
echo -ne "\033[1;31m ENTER TU NS (NAMESERVER)\033[1;37m: "; read nameserver
cd /etc/slowdns
touch infons
echo $nameserver > infons
set_ns () {
sleep 1
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/ssh/startdns 
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/ssh/restartdns
chmod +x startdns
chmod +x restartdns
sed -i "s;1234;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;1234;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo -e "\033[1;37mChequeando si existe un key\033[0m"
sleep 2
echo ""
echo -e "      \033[1;31mConectando al Satelite ... 🐲🏴   \033[0m"
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "\033[1;31mKey file found! 🐲🏴\033[0m"
sleep 1
echo ""
key () {
echo -e "\033[1;37mHow do you want to get your key?\033[0m"
echo ""
echo -e "\033[1;37m[ \033[1;31m1\033[1;37m ] | \033[1;31mUsar existente key en file\033[0m"
echo -e "\033[1;37m[ \033[1;31m2\033[1;37m ] | \033[1;31mBorrar key y generar nueva key\033[0m"
echo -e "\033[1;37m[ \033[1;31m3\033[1;37m ] | \033[1;31mDelete file and use default key\033[0m"
echo -e "\033[1;37m[ \033[1;31mx\033[1;37m ] | \033[1;31mAbortar installation\033[0m"
echo ""
echo -ne "\033[1;31mEnter la option: \033[1;37m" && read option
case $option in
1) Option1 ;;
2) Option2 ;;
3) Option3 ;;
x) OptionX ;;
*) "Unknown command" ; echo ; key;;
esac
}
Option1 () {
echo -ne "\033[1;31mRestoring existing key... 🐲🏴\033[0m" && sleep 2 && echo "OK!"
echo ""
echo -e "\033[1;37mFINISHING...\033[0m"
finish_ist () {
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 22 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED! 🐲🏴\033[0m"
echo ""
echo -ne "\033[1;31mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;31mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;31mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;31m YOUR KEY is saved in the file /root/server.pub 🐲🏴\033[0m"
echo -e "\033[1;31mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
Option2 () {
cd
rm server.key server.pub
echo -e "\033[1;31mGenerating new key 🐲🏴\033[0m"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "\033[1;37mFINISHING...\033[0m"
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 22 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED! 🐲🏴\033[0m"
echo ""
echo -ne "\033[1;31mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;31mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;31mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;31m YOUR KEY is saved in the file /root/server.pub 🐲🏴\033[0m"
echo -e "\033[1;31mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
Option3 () {
echo -e "\033[1;31mDownloading default key pair... 🐲🏴\033[0m"
cd
rm server.key server.pub
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.key
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.pub
sleep 1
echo -e "\033[1;31mDownload Completed 🐲🏴\033[0m"
sleep 1
cd /etc/slowdns/
echo -e "\033[1;37mFINISHING...\033[0m"
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 22 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED! 🐲🏴\033[0m"
echo ""
echo -ne "\033[1;31mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;31mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;31mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;31m YOUR KEY is saved in the file /root/server.pub 🐲🏴\033[0m"
echo -e "\033[1;31mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
OptionX () {
exit
}
key
else
echo -e "\033[1;31mThere is no key in the logs 🐲🏴\033[0m"
echo ""
key_gen () {
echo -e "\033[1;37mHow do you want to get your key?\033[0m"
echo ""
echo -e "\033[1;37m[ \033[1;31m1\033[1;37m ] | \033[1;31mGenerar en la installacion\033[0m"
echo -e "\033[1;37m[ \033[1;31m2\033[1;37m ] | \033[1;31mUsar the default key\033[0m"
echo -e "\033[1;37m[ \033[1;31mx\033[1;37m ] | \033[1;31mAbort installation\033[0m"
echo ""
echo -ne "\033[1;31mEnter an option: \033[1;37m" && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Unknown command" ; echo ; key_gen;;
esac
}
opc_key1 () {
echo -e "\033[1;31mGenerating your key... 🐲🏴\033[0m"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "\033[1;37mFINISHING...\033[0m"
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 22 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALLATION COMPLETED! 🐲🏴\033[0m"
echo ""
echo -ne "\033[1;31mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;31mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;31mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;31m YOUR KEY is saved in the file /root/server.pub 🐲🏴\033[0m"
echo -e "\033[1;31mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
opc_key2 () {
echo -e "\033[1;31mDownloading default key pair... 🐲🏴\033[0m"
cd
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.key
wget https://raw.githubusercontent.com/khaledagn/DNS-AGN/main/server.pub
sleep 1
echo -e "\033[1;31mDownload Completed 🐲🏴\033[0m"
sleep 1
cd /etc/slowdns/
echo -e "\033[1;37mFINISHING...\033[0m"
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 22 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALACION COMPLETO! 🐲🏴\033[0m"
echo ""
echo -ne "\033[1;31mYOUR NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;31mYOUR PUBLIC KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;31mTERMUX COMMAND:\033[0m curl -sO https://github.com/khaledagn/DNS-AGN/raw/main/files/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;31m YOUR KEY is saved in the file /root/server.pub 🐲🏴\033[0m"
echo -e "\033[1;31mKeep it in a safe place, you may need it in the future!\033[0m"
echo ""
read -p "Press [Enter] to return to the menu or CTRL+C to exit"
slowdns
}
opc_keyx () {
echo -e "\033[1;31mAborting installation 🐲🏴\033[0m"
sleep 2
slowdns
}
key_gen
fi
